global using SunamoFileIO._sunamo.SunamoExceptions;
global using SunamoFileIO._sunamo.SunamoExtensions;
global using SunamoFileIO._sunamo.SunamoFileSystem;
global using SunamoFileIO._sunamo.SunamoStringGetLines;
global using System;
global using System.Collections.Generic;
global using System.Data;
global using System.Diagnostics;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Text;
global using System.Threading.Tasks;
global using FileMs = System.IO.File;
global using SunamoFileIO;
global using SunamoFileIO.CallOnlyFileIO;

global using ILogger = Microsoft.Extensions.Logging.ILogger;
global using Microsoft.Extensions.Logging;
global using NullLogger = Microsoft.Extensions.Logging.Abstractions.NullLogger;
